#pragma once
#include <Assets/AssetManager.h>
#include <Assets/Mesh.h>
#include <Assets/DefaultMeshes.h>
#include <Assets/Material.h>
#include <Assets/MaterialTypes.h>
#include <Assets/Image.h>
#include <Assets/ImageData.h>
#include <Assets/Animations.h>
#include <Assets/AudioClip.h>
#include <Assets/Script.h>
#include <Assets/SavedScene.h>
#include <Assets/Shader.h>
#include <Assets/Font.h>
