#pragma once
#include <Engine\Assets\Mesh.h>
#include <Engine\Assets\DefaultMeshes.h>
#include <Engine\Assets\Material.h>
#include <Engine\Assets\MaterialInstance.h>
#include <Engine\Assets\MaterialTypes.h>
#include <Engine\Assets\Texture.h>
#include <Engine\Assets\DefaultTextures.h>
#include <Engine\Assets\Image.h>
